### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by BrandonR9** [csctd/profile-website-BrandonR9#5]
- [ ] Colorblind
- [ ] Text to speech
- [ ] store tab
- [ ] Slideshow

**Comment by BrandonR9** [comment]
![IMG_3107](https://github.com/csctd/profile-website-BrandonR9/assets/141273653/61e79aa7-64a0-4083-9c30-869c272775c2)

**Comment by sarmenti7** [comment]
Perfect!
